<?php

/**
 * Checks if the HTTP headers contain the Walkhub Proxy's own header.
 *
 * @return bool
 */
function walkhub_client_check_headers() {
  $headers = array();

  if (function_exists('getallheaders')) {
    $headers = getallheaders();
  }
  elseif (function_exists('apache_request_headers')) {
    $headers = apache_request_headers();
  }

  return $headers && !empty($headers['X-Walkhub-Client']);
}

/**
 * Checks if the walkhub client is enabled on the current path.
 *
 * Modules can disable or enable the walkhub client on certain paths
 * by implementing hook_walkhub_client_paths().
 *
 * @return bool
 */
function walkhub_client_is_enabled() {
  $patterns = module_invoke_all('walkhub_client_paths');

  if ($patterns) {
    return drupal_match_path($_GET['q'], implode(PHP_EOL, $patterns));
  }

  // If nothing implements the hook then allow on all paths.
  return TRUE;
}

/**
 * Implements hook_init().
 */
function walkhub_client_init() {
  if (walkhub_client_check_headers() || !walkhub_client_is_enabled()) {
    return;
  }

  if ($hub = variable_get('walkhub_hub_origin', 'http://walkhub.net')) {
    $resources_base = $hub . '/resources/';

    // We want to reload files on cache clear.
    $query_string = variable_get('css_js_query_string', '0');

    drupal_add_js("$resources_base/compiled.js?$query_string", array(
      'type' => 'external',
      'cache' => FALSE,
      'preprocess' => FALSE,
    ));
    drupal_add_js(drupal_get_path('module', 'walkhub_client') . '/walkhub.js');
    drupal_add_js(array(
      'walkhub_client' => array(
        'origin' => $hub,
      ),
    ), array('type' => 'setting'));
    drupal_add_css("$resources_base/walkthrough.css?$query_string", array(
      'type' => 'external',
      'preprocess' => FALSE,
    ));
  }
}

/**
 * Implements hook_menu().
 */
function walkhub_client_menu() {
  $items = array();

  $items['admin/config/services/walkhub_client'] = array(
    'title' => 'Walkhub client configuration',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer walkhub client'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('walkhub_client_configuration_form'),
    'file' => 'walkhub_client.admin.inc'
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function walkhub_client_permission() {
  return array(
    'administer walkhub client' => array(
      'title' => t('Administer walkhub client'),
    ),
  );
}
